config/routes.rb
Rails.application.routes.draw do
  root to: 'uploads#new'

  resources :uploads, only: [:index, :show, :new, :create]
  get '/image/:filename', to: 'uploads#by_filename', as: 'image'

  get 'search/find_nearby', as: 'search'
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_many :upload_requests

  has_attached_file :image,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\z/

  geocoded_by :ip_address
  after_validation :geocode

  before_create :randomize_file_name

  private

  def randomize_file_name
    random_number = SecureRandom.hex(3)
    self.image_file_name = "#{random_number}-#{self.image_file_name}"
  end
end

app/models/upload_request.rb
class UploadRequest < ActiveRecord::Base
  belongs_to :upload

  geocoded_by :ip_address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def remote_ip
    if request.remote_ip == '127.0.0.1' || request.remote_ip == '::1'
      # Hard coded remote address so we can test it local
      '78.22.187.80'
    else
      request.remote_ip
    end
  end

  def create_markers(resource)
    markers = Gmaps4rails.build_markers(resource.geocoded) do |res, marker|
      marker.lat res.latitude unless res.latitude.nil?
      marker.lng res.longitude unless res.longitude.nil?
    end
  end

  def render_404
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404", layout: false, status: :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def find_nearby
    # find uploads that are within a range of 10km
    @uploads = Upload.near(remote_ip, 20)
    @markers = create_markers(@uploads.geocoded) if @uploads
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = Upload.all
  end

  def show
    @upload = Upload.includes(:upload_requests).find(params[:id])
    render_404 if @upload.nil?
    @upload.upload_requests.create(ip_address: remote_ip)
    @markers = create_markers(@upload.upload_requests.geocoded)
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(upload_params)
    @upload.ip_address = remote_ip
    if @upload.save
      render :show
    else
      render :new
    end
  end

  def by_filename
    @upload = Upload.find_by(image_file_name: "#{params[:filename]}.#{params[:format]}")
    render_404 if @upload.nil?
    redirect_to upload_path(@upload)
  end

  private

  def upload_params
    params.require(:upload).permit(:image)
  end

  def file_name
    "#{params[:filename]}.#{params[:format]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatacampProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- For detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/navbar' %>
  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyCyRLOtHywDcCIP08jpPlyjMPfteTkOzFc" %>
  <%= yield(:after_js) %>
</body>
</html>

app/views/search/find_nearby.html.erb
<div class="search-results">
  <h1>Images uploaded nearby you:</h1>

  <% if @uploads && @uploads.size > 0 %>
    <div id="map" class="upload-image-map" style="min-height: 300px;"></div>
    <% content_for(:after_js) do %>
      <%= javascript_tag do %>
        $(document).on('ready', function() {
          handler = Gmaps.build('Google');
          handler.buildMap({ internal: { id: 'map' } }, function(){
            markers = handler.addMarkers(<%= raw @markers.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
          });
        })
      <% end %>
    <% end %>

    <div class="images-list">
      <%= render 'shared/images_list', uploads: @uploads %>
    </div>
  <% else %>
  <div class="search-results-none">
    Sorry, nobody has uploaded a picture where you are!
    <%= image_tag "http://www.gifdivision.com/uploads/4/6/0/3/46032175/028_-_wsmpayc.gif" %>
  </div>
  <% end %>
</div>

app/views/shared/_images_list.html.erb
<% uploads.each do |upload| %>
  <div class="uploads-all-single">
    <%= link_to upload_path(upload) do %>
      <%= image_tag upload.image.url(:thumb) %>
      <%= upload.image_file_name %>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-datacamp">
  <div class="container navbar-datacamp-container">
    <%= link_to uploads_path do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <div class="navbar-datacamp-pusher"></div>
    <div class="navbar-datacamp-item">
      <%= link_to "Find Nearby Images", search_path %>
    </div>
    <%= link_to "Upload Image", new_upload_path, class: "navbar-datacamp-item navbar-datacamp-button btn" %>
  </div>
</nav>

app/views/uploads/index.html.erb
<div class="uploads-all">
  <%= render 'shared/images_list', uploads: @uploads %>
</div>

app/views/uploads/new.html.erb
<div class="upload-image upload-image-form container">
  <%= form_for(@upload, html: { multipart: true }) do |f| %>
    <div class="form-group">
      <div id="kv-avatar-errors" class="center-block" style="width:800px;display:none"></div>
      <div class="kv-avatar center-block" style="width:200px">
        <%= f.file_field :image, required: true, class: "file-loading", id: 'avatar'%>
      </div>
    </div>
    <div class="form-actions">
      <%= f.button "Upload", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    var defaultImage = '<%= image_tag "logo.png", class: "player-profile-form-avatar" %>';

    $("#avatar").fileinput({
      overwriteInitial: true,
      maxFileSize: 1500,
      showClose: false,
      showCaption: false,
      browseLabel: '',
      removeLabel: '',
      browseIcon: '<i class="glyphicon glyphicon-folder-open"></i>',
      removeIcon: '<i class="glyphicon glyphicon-remove"></i>',
      removeTitle: 'Cancel or reset changes',
      elErrorContainer: '#kv-avatar-errors',
      msgErrorClass: 'alert alert-block alert-danger',
      defaultPreviewContent: defaultImage,
      layoutTemplates: {main2: '{preview} '  + ' {remove} {browse}'},
      allowedFileExtensions: ["jpg", "png", "gif", "jpeg"]
    });
  <% end %>
<% end %>

app/views/uploads/show.html.erb
<div class="upload-image">
  <div class="upload-image-details">
    The URL to this image is:
     <%= link_to image_url(filename: @upload.image_file_name), image_path(filename: @upload.image_file_name) %>
  </div>
  <div class="upload-image-content row">
    <div class="col-sm-8">
      <%= image_tag @upload.image.url(:medium) %>
    </div>
    <div class="col-sm-4">
      This image has been visited <%= pluralize @upload.upload_requests.count, 'time' %>
    </div>
    </div>
  </div>

  <div id="map" class="upload-image-map" style="min-height: 300px;"></div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>